from fraction import *
fraction1 = Fraction(1,4)
fraction2 = Fraction(0,6)
fraction3 = Fraction(2,3)
fraction4 = Fraction(50,30)
def testing():
    print('print')
    print(fraction1)
    print(fraction2)
    print(fraction3)
    print(fraction4)
    print('as_mixed_number')
    print(fraction1.as_mixed_number())
    print('+')
    print(fraction1+fraction3)
    print('-')
    print(fraction4-fraction3)
    print('*')
    print(fraction1*fraction2)
    print('/')
    print(fraction2/fraction1)
    print('** + float')
    print(fraction3**fraction1)
    print((2/3)**(1/4))
    print('==')
    print(fraction1 == fraction2)
    print(fraction1 == Fraction(1,4))
    print('--zero--')
    print(fraction1.is_zero())
    print(fraction2.is_zero())
    print('--integer--')
    print(Fraction(8,2).is_integer())
    print('--proper--')
    print(fraction1.is_proper())
    print('--unit--')
    print(fraction2.is_unit())
    print(Fraction(4,4).is_unit())
    print('--adjacent--')
    print(fraction3.is_adjacent_to(fraction4))

if __name__ == '__main__':
    testing()
